//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CareFitEntities : DbContext
    {
        public CareFitEntities()
            : base("name=CareFitEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Empresas> Empresas { get; set; }
        public DbSet<Equipamentos> Equipamentos { get; set; }
        public DbSet<EquipamentoTipos> EquipamentoTipos { get; set; }
        public DbSet<ExercicioEquipamentos> ExercicioEquipamentos { get; set; }
        public DbSet<Exercicios> Exercicios { get; set; }
        public DbSet<ExercicioTipos> ExercicioTipos { get; set; }
        public DbSet<GrupoMuscular> GrupoMuscular { get; set; }
        public DbSet<Imagens> Imagens { get; set; }
        public DbSet<Menus> Menus { get; set; }
        public DbSet<Permissoes> Permissoes { get; set; }
        public DbSet<PessoaAmigos> PessoaAmigos { get; set; }
        public DbSet<PessoaEmpresas> PessoaEmpresas { get; set; }
        public DbSet<PessoaMensagens> PessoaMensagens { get; set; }
        public DbSet<PessoaPosts> PessoaPosts { get; set; }
        public DbSet<PessoaPostTipos> PessoaPostTipos { get; set; }
        public DbSet<PessoaProfessor> PessoaProfessor { get; set; }
        public DbSet<Pessoas> Pessoas { get; set; }
        public DbSet<PessoaSolicitacaoAmizades> PessoaSolicitacaoAmizades { get; set; }
        public DbSet<PessoaSolicitacaoEmpresa> PessoaSolicitacaoEmpresa { get; set; }
        public DbSet<PessoaSolicitacaoTipo> PessoaSolicitacaoTipo { get; set; }
        public DbSet<PessoaSolicitacoes> PessoaSolicitacoes { get; set; }
        public DbSet<PessoaTipoPermissoes> PessoaTipoPermissoes { get; set; }
        public DbSet<PessoaTipos> PessoaTipos { get; set; }
        public DbSet<PessoaToken> PessoaToken { get; set; }
        public DbSet<PessoaTreino> PessoaTreino { get; set; }
        public DbSet<PessoaTreinoEfetuado> PessoaTreinoEfetuado { get; set; }
        public DbSet<Salas> Salas { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TreinoEmpresa> TreinoEmpresa { get; set; }
        public DbSet<TreinoExercicios> TreinoExercicios { get; set; }
        public DbSet<TreinoProfessor> TreinoProfessor { get; set; }
        public DbSet<Treinos> Treinos { get; set; }
        public DbSet<TreinoTipos> TreinoTipos { get; set; }
    }
}
