//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercicios
    {
        public Exercicios()
        {
            this.ExercicioEquipamentos = new HashSet<ExercicioEquipamentos>();
            this.TreinoExercicios = new HashSet<TreinoExercicios>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public int ExercicioTipoId { get; set; }
        public int RepousoMinimo { get; set; }
        public int EmpresaId { get; set; }
        public bool Ativo { get; set; }
        public int GrupoMuscularId { get; set; }
        public Nullable<int> EquipamentoId { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Equipamentos Equipamentos { get; set; }
        public virtual ICollection<ExercicioEquipamentos> ExercicioEquipamentos { get; set; }
        public virtual ExercicioTipos ExercicioTipos { get; set; }
        public virtual GrupoMuscular GrupoMuscular { get; set; }
        public virtual ICollection<TreinoExercicios> TreinoExercicios { get; set; }
    }
}
