//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public Menus()
        {
            this.Menus1 = new HashSet<Menus>();
        }
    
        public int ID { get; set; }
        public string Titulo { get; set; }
        public string ToolTip { get; set; }
        public string Icon { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public int PermisaoId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public string Ordem { get; set; }
    
        public virtual ICollection<Menus> Menus1 { get; set; }
        public virtual Menus Menus2 { get; set; }
        public virtual Permissoes Permissoes { get; set; }
    }
}
