//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissoes
    {
        public Permissoes()
        {
            this.Menus = new HashSet<Menus>();
            this.PessoaTipoPermissoes = new HashSet<PessoaTipoPermissoes>();
        }
    
        public int ID { get; set; }
        public string Chave { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Menus> Menus { get; set; }
        public virtual ICollection<PessoaTipoPermissoes> PessoaTipoPermissoes { get; set; }
    }
}
