//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaTipos
    {
        public PessoaTipos()
        {
            this.PessoaEmpresas = new HashSet<PessoaEmpresas>();
            this.PessoaTipoPermissoes = new HashSet<PessoaTipoPermissoes>();
        }
    
        public int ID { get; set; }
        public string Descricao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual ICollection<PessoaEmpresas> PessoaEmpresas { get; set; }
        public virtual ICollection<PessoaTipoPermissoes> PessoaTipoPermissoes { get; set; }
    }
}
