//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaSolicitacoes
    {
        public PessoaSolicitacoes()
        {
            this.PessoaSolicitacaoAmizades = new HashSet<PessoaSolicitacaoAmizades>();
            this.PessoaSolicitacaoEmpresa = new HashSet<PessoaSolicitacaoEmpresa>();
        }
    
        public long ID { get; set; }
        public long PessoaId { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataSolicitacao { get; set; }
        public Nullable<System.DateTime> DataResposta { get; set; }
        public int PessoaSolicitacaoTipoId { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
        public virtual ICollection<PessoaSolicitacaoAmizades> PessoaSolicitacaoAmizades { get; set; }
        public virtual ICollection<PessoaSolicitacaoEmpresa> PessoaSolicitacaoEmpresa { get; set; }
        public virtual PessoaSolicitacaoTipo PessoaSolicitacaoTipo { get; set; }
    }
}
