//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaTreino
    {
        public PessoaTreino()
        {
            this.PessoaTreinoEfetuado = new HashSet<PessoaTreinoEfetuado>();
        }
    
        public long ID { get; set; }
        public long PessoaId { get; set; }
        public long TreinoId { get; set; }
        public System.DateTime Inicio { get; set; }
        public Nullable<System.DateTime> Termino { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
        public virtual Treinos Treinos { get; set; }
        public virtual ICollection<PessoaTreinoEfetuado> PessoaTreinoEfetuado { get; set; }
    }
}
