//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaMensagens
    {
        public long ID { get; set; }
        public long PessoaRemetenteId { get; set; }
        public long PessoaDestinatarioId { get; set; }
        public string Mensagem { get; set; }
        public System.DateTime DataEnvio { get; set; }
        public Nullable<System.DateTime> DataVisualizado { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
        public virtual Pessoas Pessoas1 { get; set; }
    }
}
