//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaSolicitacaoEmpresa
    {
        public long ID { get; set; }
        public long PessoaSolicitacaoId { get; set; }
        public int EmpresaId { get; set; }
        public bool Resposta { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual PessoaSolicitacoes PessoaSolicitacoes { get; set; }
    }
}
