//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaPosts
    {
        public long ID { get; set; }
        public long PessoaId { get; set; }
        public int PessoaPostTipoId { get; set; }
        public System.DateTime DataPost { get; set; }
        public string Post { get; set; }
    
        public virtual PessoaPostTipos PessoaPostTipos { get; set; }
        public virtual Pessoas Pessoas { get; set; }
    }
}
