//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaTipoPermissoes
    {
        public int ID { get; set; }
        public int PermissaoID { get; set; }
        public int PessoaTipoID { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Permissoes Permissoes { get; set; }
        public virtual PessoaTipos PessoaTipos { get; set; }
    }
}
