//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaPostTipos
    {
        public PessoaPostTipos()
        {
            this.PessoaPosts = new HashSet<PessoaPosts>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PessoaPosts> PessoaPosts { get; set; }
    }
}
