//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treinos
    {
        public Treinos()
        {
            this.PessoaTreino = new HashSet<PessoaTreino>();
            this.TreinoEmpresa = new HashSet<TreinoEmpresa>();
            this.TreinoExercicios = new HashSet<TreinoExercicios>();
            this.TreinoProfessor = new HashSet<TreinoProfessor>();
        }
    
        public long ID { get; set; }
        public int Repeticoes { get; set; }
        public int RepousoMinimo { get; set; }
        public int TreinoTipoId { get; set; }
        public long PessoaCadastroTreino { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string Cor { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
        public virtual ICollection<PessoaTreino> PessoaTreino { get; set; }
        public virtual ICollection<TreinoEmpresa> TreinoEmpresa { get; set; }
        public virtual ICollection<TreinoExercicios> TreinoExercicios { get; set; }
        public virtual ICollection<TreinoProfessor> TreinoProfessor { get; set; }
        public virtual TreinoTipos TreinoTipos { get; set; }
    }
}
