//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreinoProfessor
    {
        public long ID { get; set; }
        public long PessoaId { get; set; }
        public System.DateTime Cadastro { get; set; }
        public Nullable<System.DateTime> Cancelado { get; set; }
        public long TreinoId { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
        public virtual Treinos Treinos { get; set; }
    }
}
