//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreinoExercicios
    {
        public int ID { get; set; }
        public int ExercicioId { get; set; }
        public long TreinoId { get; set; }
        public int Repeticoes { get; set; }
        public int Ciclos { get; set; }
        public Nullable<int> Carga { get; set; }
        public int Descanso { get; set; }
    
        public virtual Exercicios Exercicios { get; set; }
        public virtual Treinos Treinos { get; set; }
    }
}
