//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFit.Domain.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreinoTipos
    {
        public TreinoTipos()
        {
            this.Treinos = new HashSet<Treinos>();
        }
    
        public int ID { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Treinos> Treinos { get; set; }
    }
}
